version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: America/Vancouver
    open-pull-requests-limit: 10
    labels:
      - dependencies
    commit-message:
      prefix: deps
      include: scope
    groups:
      androidx:
        patterns:
          - "androidx.*"
      firebase:
        patterns:
          - "com.google.firebase:*"
          - "com.google.gms:*"
      dagger-hilt:
        patterns:
          - "com.google.dagger:*"
          - "androidx.hilt:*"
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
