#!/bin/bash
# Script to backup unused drawable files
BACKUP_DIR="unused_drawables_backup_$(date +%Y%m%d_%H%M%S)"
mkdir -p "$BACKUP_DIR"
echo "Backing up unused drawables to $BACKUP_DIR..."
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/button_premium_rounded.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/ic_water_bottle.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/progress_dot_background.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/card_white_background.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/otp_numpad_button_background.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/ic_arrow_forward.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/ic_backspace.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/confetti.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/water_filling_gradient.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/numpad_button_secondary.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/ic_check_circle.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/otp_clear_button_background.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/gradient_background_vending.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/gradient_background_animation.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/sparkle.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/card_enhanced_shadow_background.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/progress_dot.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/card_gradient_background.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/ic_sms.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/card_gradient_qr.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/heart.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/pulsing_circle_background.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/phone_display_background.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/gradient_background_qr.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/keypad_special_button_background.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/otp_digit_background.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/card_disabled_background.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/bottle_highlight.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/card_gradient_sms.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/button_glow_background.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/numpad_button_background.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/ic_send.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/dot_pattern_overlay.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/water_bottle_empty.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/gradient_background_sms.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/numpad_button_professional.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/keypad_button_background.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/water_bottle_filled.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/card_glass_background.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/water_drop.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/phone_input_background.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/otp_delete_button_background.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/vending_glow_background.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/countdown_circle_background.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/dispensing_indicator_background.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/water_bottle_shadow.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/ic_water_drop.xml" "$BACKUP_DIR/"
cp "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/water_bubble.xml" "$BACKUP_DIR/"
echo "Backup complete! Files saved to $BACKUP_DIR"
