#!/bin/bash
# Script to delete unused drawable files
# WARNING: This will permanently delete files. Make sure you have a backup!
echo "This will delete unused drawable files."
read -p "Are you sure you want to continue? (yes/no): " confirm
if [ "$confirm" != "yes" ]; then
    echo "Deletion cancelled."
    exit 0
fi
echo "Deleting unused drawables..."
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/button_premium_rounded.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/ic_water_bottle.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/progress_dot_background.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/card_white_background.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/otp_numpad_button_background.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/ic_arrow_forward.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/ic_backspace.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/confetti.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/water_filling_gradient.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/numpad_button_secondary.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/ic_check_circle.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/otp_clear_button_background.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/gradient_background_vending.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/gradient_background_animation.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/sparkle.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/card_enhanced_shadow_background.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/progress_dot.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/card_gradient_background.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/ic_sms.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/card_gradient_qr.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/heart.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/pulsing_circle_background.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/phone_display_background.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/gradient_background_qr.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/keypad_special_button_background.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/otp_digit_background.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/card_disabled_background.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/bottle_highlight.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/card_gradient_sms.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/button_glow_background.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/numpad_button_background.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/ic_send.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/dot_pattern_overlay.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/water_bottle_empty.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/gradient_background_sms.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/numpad_button_professional.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/keypad_button_background.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/water_bottle_filled.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/card_glass_background.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/water_drop.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/phone_input_background.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/otp_delete_button_background.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/vending_glow_background.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/countdown_circle_background.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/dispensing_indicator_background.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/water_bottle_shadow.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/ic_water_drop.xml"
rm -f "/Users/karimeldegwy/Desktop/Projects/waterfountain-vending/app/src/main/res/drawable/water_bubble.xml"
echo "Deletion complete!"
echo "You can now run ./gradlew clean build to verify the build still works."
